version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MQTT_HOST="mqtt"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
  mqtt:
    image: toke/mosquitto
    ports:
      - "1883:1883"
